### ISSUE TITLE
Problem with AbstractGUI

### ISSUE THREAD

**Issue by elraro** [Year4000/Meta#18]
Finally i find the java.lang.ArrayIndexOutOfBoundsException: 3 bug.

1) Create a GUI. Open it ingame.

2) Click in the last row of YOUR inventory with the GUI opened. Java Exception.

Im using the last version.

**Comment by ewized** [comment]
Thats good to know, I will take a look into it.

**Comment by ewized** [comment]
I looked into this, and this was already fixed. https://github.com/Year4000/Utilities/blob/master/bukkit/src/main/java/net/year4000/utilities/bukkit/gui/AbstractGUI.java#l72

**Comment by elraro** [comment]
Hi. Yeah, im using this fix in the last version and i still getting the Java Exception
